Added unban
shughes-uk/python-youtubechat pull request #6
Opened 2017-09-24 09:46 UTC by Crypti-x

I made this code a bit better c:

2017-09-24 16:44 UTC, shughes-uk requested changes

2017-09-24 16:44 UTC, shughes-uk commented on youtubechat/ytchat.py
> +import sys
both json and sys are already imported you don't need this line

2017-09-24 16:44 UTC, shughes-uk commented on youtubechat/ytchat.py
> +        popo = json.dumps(data)
please rename this variable to 'returnjson' or something similar. you can also just do dumps(data) instead of json.dumps(data)

2017-09-27 17:47 UTC, Crypti-x commented
so.

2017-09-27 18:02 UTC, shughes-uk commented
Looks good, thanks!

2017-09-27 18:02 UTC, merged